language: python
sudo: required
services:
  - docker
python:
  - "2.7"
install:
  - pip install -r Tornado-Application/requirements.txt

before_install:
  - docker build -t  mxlei01/test_travis_repo .
  - docker ps -a

script: cd /application/Tornado-Application && python -m tornado.test.runtests test
